const
  icsMain* = """
BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:$1
VERSION:2.0
BEGIN:VTIMEZONE
TZID:$2
BEGIN:STANDARD
DTSTART:$3
TZOFFSETFROM:$4
TZOFFSETTO:$5
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:$3
TZOFFSETFROM:$4
TZOFFSETTO:$5
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
"""

  icsOrganizer* = "ORGANIZER;CN=$1:mailto:$2" # Name, Email

  icsAttendees*  = "ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=$3;CN=$1:mailto:$2" # Name, Email

  icsDescription* = "DESCRIPTION;LANGUAGE=$1:$2" # Lang (e.g. da-DK), Description

  icsSummary* = "SUMMARY;LANGUAGE=$1:$2" # Lang (e.g. da-DK), Summary

  icsUid* = "UID:$1"

  icsDetails* = """
DTSTART;TZID=$1:$2
DTEND;TZID=$1:$3
CLASS:$4
PRIORITY:$5
DTSTAMP:$6
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:$9
LOCATION;LANGUAGE=$7:$8
"""

  icsAlarm* = """
BEGIN:VALARM
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:-PT$1
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR"""